### ISSUE TITLE
Additional Bayes algorithms

### ISSUE THREAD

**Issue by railsmechanic** [fredwu/simple_bayes#1]
First, many thanks for your great Bayes library!

As an enhancement and to handle different use cases, it would be great to have the ability to select the Bayes algorithm to use.

I would suggest these two additional algorithms:
- **Binarized Multinomial Naive Bayes** _(The Binarized Multinomial Naive Bayes can be used when the frequencies of the words don’t play a key role in a classification, e.g. sentiment analysis)_
- **Bernoulli Naive Bayes** _(The Bernoulli Naive Bayes can be used when the absence of a particular word matters, e.g. spam or adult content filtering)_

What do you think?

**Comment by fredwu** [comment]
Hi,

Thanks for the suggestion! I had thought about it before but ended up with only Multinomial so it's more useful to me. I'd love to investigate and see how complex it is to add different algorithms - no promises though. :)

If you or anyone would like to contribute that would be awesome! ❤️

**Comment by railsmechanic** [comment]
Let me see what I can do... 😃

**Comment by fredwu** [comment]
Binarized multinomial model is implemented! 😈 https://github.com/fredwu/simple_bayes/commit/281cb36f42ee547e6d3f464380a943ccca8b9066

**Comment by railsmechanic** [comment]
👍  You rock!!!

**Comment by fredwu** [comment]
Bernoulli implemneted: 0c8017d3937d86aeb0fe8ee1b2279e9be0a8964e

Please let me know if it works well. :)
